[mypy]
python_version = 3.11
strict = False
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = True
exclude = tests/

[mypy-chromadb.*]
ignore_missing_imports = True

[mypy-tiktoken.*]
ignore_missing_imports = True

[mypy-numpy.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True
